### ISSUE TITLE
Create Card Deck for 'IT-Sicherheit' lecture

### ISSUE THREAD

**Issue by AndreiBerbescu** [fancy-flashcard/ffc#32]

**Comment by nikolockenvitz** [comment]
Any updates or can this issue be closed?

![r2](https://user-images.githubusercontent.com/10072099/120791530-9f81fe80-c534-11eb-9f0f-02cefba85656.png)

**Comment by michael-spengler** [comment]
https://github.com/fancy-flashcard/wirtschaftsinformatik
