### ISSUE TITLE
Create Card Deck for "Unternehmensführung"

### ISSUE THREAD

**Issue by MrFloK** [fancy-flashcard/ffc#33]

**Comment by nikolockenvitz** [comment]
Any updates or can this issue be closed?

![r3b](https://user-images.githubusercontent.com/10072099/120791541-a27cef00-c534-11eb-9c39-e48c859f576c.png)

**Comment by michael-spengler** [comment]
https://github.com/fancy-flashcard/wirtschaftsinformatik/blob/main/unternehmensfuehrung.json
