### ISSUE TITLE
Create Card Deck for "Finanzbuchhaltung"

### ISSUE THREAD

**Issue by MrFloK** [fancy-flashcard/ffc#34]

**Comment by nikolockenvitz** [comment]
Any updates or can this issue be closed?

![r4](https://user-images.githubusercontent.com/10072099/120791555-a6107600-c534-11eb-9d95-4b8ba15401e5.png)

**Comment by michael-spengler** [comment]
https://github.com/fancy-flashcard/wirtschaftsinformatik/blob/main/Finanzbuchhaltung.json
