### ISSUE TITLE
Create Card Deck for 'Programmieren I & II' lecture

### ISSUE THREAD

**Issue by AndreiBerbescu** [fancy-flashcard/ffc#35]

**Comment by nikolockenvitz** [comment]
Any updates or can this issue be closed?

![r5b](https://user-images.githubusercontent.com/10072099/120791566-a7da3980-c534-11eb-87c4-71683679da79.png)

**Comment by michael-spengler** [comment]
https://github.com/fancy-flashcard/wirtschaftsinformatik/issues/30
