### ISSUE TITLE
Create Card Deck for 'Kryptographie'

### ISSUE THREAD

**Issue by AndreiBerbescu** [fancy-flashcard/ffc#36]

**Comment by nikolockenvitz** [comment]
Any updates or can this issue be closed?

![r6b](https://user-images.githubusercontent.com/10072099/120791574-aa3c9380-c534-11eb-9a85-ae32e34bdd96.png)

**Comment by michael-spengler** [comment]
closing this --> following things up via: https://github.com/fancy-flashcard/wirtschaftsinformatik/issues/30 when the time is right.
